export default [
  {
    title: 'Panel',
    icon: { icon: 'tabler-smart-home' },
    to: 'dashboard',
    action: 'read',
    subject: 'Dashboard',
  },
  {
    title: 'Projeler',
    icon: { icon: 'tabler-building-skyscraper' },
    to: 'projects',
    action: 'read',
    subject: 'Project',
  },
  {
    title: 'Müşteriler',
    icon: { icon: 'tabler-users' },
    to: 'clients',
    action: 'read',
    subject: 'Client',
  },
  {
    title: 'Teklifler',
    icon: { icon: 'tabler-file-invoice' },
    to: 'quotes',
    action: 'read',
    subject: 'Quote',
  },
  {
    title: 'Muhasebe',
    icon: { icon: 'tabler-report-money' },
    to: 'accounting',
    action: 'read',
    subject: 'Transaction',
  },
  {
    title: 'Hesap Araçları',
    icon: { icon: 'tabler-calculator' },
    to: 'calculators',
    action: 'read',
    subject: 'Calculator',
  },
  {
    title: 'Harita',
    icon: { icon: 'tabler-map-2' },
    to: 'map',
    action: 'read',
    subject: 'Measurement',
  },
  {
    title: 'Personel',
    icon: { icon: 'tabler-user-cog' },
    to: 'staff',
    action: 'read',
    subject: 'Staff',
  },
  {
    title: 'Site Ayarları',
    icon: { icon: 'tabler-world' },
    to: 'settings-site',
    action: 'manage',
    subject: 'TenantSettings',
  },
  {
    title: 'Platform Yönetimi',
    icon: { icon: 'tabler-shield-cog' },
    to: 'admin-tenants',
    action: 'manage',
    subject: 'PlatformAdmin',
  },
]
